### PR TITLE
Change MENU key to APP_SWITCH

### PR DESCRIPTION
**Pull request by max20091**

### CODE REVIEW

**Comment by tank0412** [comment]
And what it will do?

**Comment by max20091** [comment]
just swap MENU to APP_SWITCH for convenient
anyway, RR doesn't have setting to change the action this button use it

**Comment by tank0412** [comment]
I understand but in our case hardware buttons does not work at all.

**Comment by max20091** [comment]
Only HOME button is not working (Key 102, must be ROM issue)
Key 195 and 158 still work normally
Edit: maybe the ROM issue idk, I changed in the system folder but it seems not working  :(

**Comment by tank0412** [comment]
Ok. I will check it later.

**Comment by max20091** [comment]
It seems that issue is come from the ROM, I changed to APP_SWITCH but the button still assigned to MENU
You can download the KeynumberTracker and see if it work, I pressed all 3 buttons and it say the right number => maybe ROM issue

**Comment by max20091** [comment]
I found the reason why the button is not working as expected #2

**Pull request closed without merging**
