### PR TITLE
Create Generic.kl for touch button fix

### PR DESCRIPTION
**Pull request by max20091**

### CODE REVIEW

**Comment by max20091** [comment]
Key layout:
114 vol down
115 vol up
195 app switch
102 home
158 back
#2 
I'm sorry if I annoying you :(

**Comment by tank0412** [comment]
Man, nobody adds prebuilt Generic.kl to proprietary.
It is really strange. Must be another solution.

**Comment by max20091** [comment]
Dunno, just do what you want :D
So move it to where?
I think I can only place it to here.

**Comment by harrynowl** [comment]
The original Mi Pad also has this issue, and I believe the guys fixed it this way by replacing the Generic.kl too. There's probably a better solution out there but the workaround here isn't detrimental either.

**Pull request merged**
